using System.Collections.Generic;

namespace Systems.Clearance.Utils
{
	public static class MigrationData
	{
		public static readonly Dictionary<Access, Clearance> Translation = new Dictionary<Access, Clearance>
		{
			{Access.ai_upload, Clearance.AIUpload},
			{Access.armory, Clearance.Armory},
			{Access.atmospherics, Clearance.Atmospherics},
			{Access.bar, Clearance.Bar},
			{Access.brig, Clearance.Brig},
			{Access.captain, Clearance.Captain},
			{Access.cargo, Clearance.Cargo},
			{Access.cargo_bot, Clearance.Cargo},
			{Access.ce, Clearance.Ce},
			{Access.change_ids, Clearance.ChangeIds},
			{Access.chapel_office, Clearance.ChapelOffice},
			{Access.chemistry, Clearance.Chemistry},
			{Access.clown, Clearance.ClownOffice},
			{Access.cmo, Clearance.Cmo},
			{Access.construction, Clearance.Construction},
			{Access.court, Clearance.Court},
			{Access.crematorium, Clearance.Crematorium},
			{Access.engine_room, Clearance.Engine },
			{Access.engineering, Clearance.Engine},
			{Access.eva, Clearance.Eva},
			{Access.external_airlocks, Clearance.ExternalAirlocks},
			{Access.forensics_lockers, Clearance.ForensicsLockers},
			{Access.gateway, Clearance.Gateway},
			{Access.genetics, Clearance.Genetics},
			{Access.heads, Clearance.Heads},
			{Access.heads_vault, Clearance.Vault},
			{Access.hop, Clearance.Hop},
			{Access.hos, Clearance.Hos},
			{Access.hydroponics, Clearance.Hydroponics},
			{Access.janitor, Clearance.Janitor},
			{Access.keycard_auth, Clearance.KeycardAuth},
			{Access.kitchen, Clearance.Kitchen},
			{Access.lawyer, Clearance.Lawyer},
			{Access.library, Clearance.Library},
			{Access.mailsorting, Clearance.Mailsorting},
			{Access.maint_tunnels, Clearance.MaintTunnels},
			{Access.medical, Clearance.Medical},
			{Access.mime, Clearance.MimeOffice},
			{Access.mining, Clearance.Mining},
			{Access.mining_office, Clearance.Cargo},
			{Access.mining_station, Clearance.MiningStation},
			{Access.morgue, Clearance.Morgue},
			{Access.psychiatrist, Clearance.Psychology},
			{Access.qm, Clearance.Qm},
			{Access.RC_announce, Clearance.RcAnnounce},
			{Access.rd, Clearance.Rd},
			{Access.rnd_lab, Clearance.Rnd},
			{Access.robotics, Clearance.Robotics},
			{Access.science, Clearance.Research},
			{Access.sec_doors, Clearance.SecDoors},
			{Access.security, Clearance.Security},
			{Access.surgery, Clearance.Surgery},
			{Access.syndicate, Clearance.Syndicate},
			{Access.tcomsat, Clearance.Tcomsat},
			{Access.tech_storage, Clearance.TechStorage},
			{Access.teleporter, Clearance.Teleporter},
			{Access.theatre, Clearance.Theatre},
			{Access.tox_storage, Clearance.ToxinsStorage},
			{Access.virology, Clearance.Virology},
			{Access.weapons, Clearance.Weapons},
			{Access.xenobiology, Clearance.Xenobiology},
			{Access.centcom, Clearance.CentGeneral}
		};
	}
}