using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Antagonists
{
	/// <summary>
	/// The base class ScriptableObject for all antagonist objectives
	/// </summary>
	public abstract class Objective : ScriptableObject
	{
		/// <summary>
		/// The name of the objective type
		/// </summary>
		[SerializeField]
		protected string objectiveName;
		/// <summary>
		/// The name of the objective type
		/// </summary>
		public string ObjectiveName => objectiveName;

		/// <summary>
		/// The description of the objective which is shown to players. Usually generated by the objective when it is setup.
		/// </summary>
		[SerializeField]
		protected string description;
		/// <summary>
		/// The description of the objective which is shown to players. Usually generated by the objective when it is setup.
		/// </summary>
		public string Description => description;

		/// <summary>
		/// Check if this objective is possible, defaults to true if not set
		/// </summary>
		public virtual bool IsPossible()
		{
			return true;
		}

		/// <summary>
		/// Perform initial setup of the objective if needed
		/// </summary>
		public virtual void Setup(PlayerScript thisPlayer) {}

		/// <summary>
		/// Defines how to check the completion of the objective using a reference to the player's PlayerNetworkActions
		/// </summary>
		public abstract bool IsComplete(PlayerScript thisPlayer);
	}
}