"Scene Changes":
  - UnityProject/Assets/StreamingAssets/Maps/**/*.json
  - UnityProject/Assets/**/*.unity

"Scene: SquareStation":
  - UnityProject/Assets/StreamingAssets/Maps/MainStations/SquareStation.json

"Scene: PogStation":
  - UnityProject/Assets/StreamingAssets/Maps/MainStations/PogStation.json

"Scene: FallStation":
  - UnityProject/Assets/StreamingAssets/Maps/MainStations/FallStation.json

"Scene: OutpostStation":
  - UnityProject/Assets/StreamingAssets/Maps/MainStations/OutpostStation.json

"Scene: BoxStation":
  - UnityProject/Assets/StreamingAssets/Maps/MainStations/BoxStationV1.json

"Scene: UnrealStation":
  - UnityProject/Assets/StreamingAssets/Maps/MainStations/UnRealStation.json

"Scene: MiniStation":
  - UnityProject/Assets/StreamingAssets/Maps/MainStations/MiniStation.json

"Documentation":
  - docs/**/*

"Sprite Work":
  - UnityProject/Assets/Textures/**/*.png
  - UnityProject/Assets/Textures/**/*.PNG
  - AssetLibrary/**/*.png
  - AssetLibrary/**/*.PNG

"UI":
  - UnityProject/Assets/Scripts/UI/**/*
  - UnityProject/Assets/Scenes/UI/**/*
