ChatBubbles:
  Default:
    ImageColor: "#FFFFFF"
    TextColor: "#000000"
  DarkTheme:
    ImageColor: "#222222"
    TextColor: "#FFFFFF"

# Either add to this file or start a new
# one for your custom theme