# Project Information
site_name: UnityStation
site_description: "Project Design and Documentation for development"
site_author: "MrMepper"
site_url: "https://unitystation.github.io/unitystation/"

# Repository
repo_name: "unitystation/unitystation"
repo_url: "https://github.com/unitystation/unitystation/"
edit_uri: "edit/develop/docs/"

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: en
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - search.suggest

plugins:
  - search
