blank_issues_enabled: true
contact_links:
  - name: Issues with the launcher
    url:  https://github.com/unitystation/stationhub/issues/new/choose
    about: Please open issues relating to StationHub in unitystation/stationhub.
