version: "3.7"

services:
  unitystation:
    image: unitystation/unitystation:develop
    ports:
      - 7777:7777/udp
      - 7777:7777/tcp
      - 7778:7778/tcp
    environment:
      SERVER_NAME: Unitystation - EU02 Staging
      DISCORDLINKID: $DISCORDLINKID
    labels:
      - io.portainer.accesscontrol.public
    volumes:
      - /root/staging/secrets.json:/server/Unitystation_Data/StreamingAssets/Config/secrets.json
      - /root/staging/gameConfig.json:/server/Unitystation_Data/StreamingAssets/Config/gameConfig.json
      - /root/staging/gameConfig.json:/server/Unitystation_Data/StreamingAssets/Config/rules.txt
      - /root/staging/playTestServerDesc.txt:/server/Unitystation_Data/StreamingAssets/Config/serverDesc.txt
      - /root/staging/profiles:/server/Unitystation_Data/StreamingAssets/Config/Profiles
      - /root/staging/admin:/server/Unitystation_Data/StreamingAssets/Config/admin
