# Cleans our artifacts in a schedule

name: ArtifactJanitor
on:
  # runs every monday at midnight UTC
  schedule:
    - cron: "0 0 * * mon"

jobs:
  cleaning:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "1 week"
          skip-tags: true
