name: DocsReminder
on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  docsReminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DocsReminder
        uses: corp-0/update-docs-pls@master
        id: DocsReminder

      - name: Comment PR
        if: ${{ steps.DocsReminder.outputs.found_doc_related_changes == 1}}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ steps.DocsReminder.outputs.comment_content }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
