########## HOW TO UPDATE UNITY_LICENSE ##########
# This workflow is only used to request a new activation file
#
# !!! WARNING: Use a throw away Unity account for this since anyone will have access to the license file !!!
#
# If you need a new one follow these steps:
# 1. Manually run this job via the Actions tab (if you are a project maintainer)
# 2. Download the manual activation file that appears as an artifact in a zip (Unity_v20XX.x.alf).
# 3. Visit license.unity3d.com, sign in and upload it.
# 4. You should now receive your license file (Unity_v20XX.x.ulf) as a download.
# 5. Replace UnityLicense.ulf in the Tools directory with it.
#
# - Make sure LICENSE_FILE_PATH in the 'Setup license' steps of the other workflows still point to it.

name: Get Unity license

on: workflow_dispatch

jobs:
  # Request license file job
  requestManualActivationFile:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      # Request manual activation file
      - name: Request manual activation file
        uses: game-ci/unity-request-activation-file@v2.0-alpha-1
        id: getManualLicenseFile
        with:
          unityVersion: 2021.1.14f1
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
