name: Tests

on:
  push:
    branches: [ develop ]
    paths:
      - "Tools/UnityLicense.ulf"
      - "UnityProject/**"
      - ".github/workflows/**"
      - "Docker/**"
  pull_request_target:
    branches: [ develop ]
    paths:
      - "Tools/UnityLicense.ulf"
      - "UnityProject/**"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:                             
  UNITY_VERSION: 6000.0.48f1
  PROJECT_PATH: UnityProject
  TARGET_PLATFORM: StandaloneWindows64

jobs:
  performTest:
    runs-on: ubuntu-latest
    environment: ci

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: ${{ env.PROJECT_PATH }}/Library
        key:  Library2-${{ env.PROJECT_PATH }}-${{ env.UNITY_VERSION }}-${{ runner.os }}
        restore-keys: |
          Library2-${{ env.PROJECT_PATH }}-${{ env.UNITY_VERSION }}-
          Library2-${{ env.PROJECT_PATH }}-

    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 8

    - name: Run tests
      id: tests
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath:   ${{ env.PROJECT_PATH }}
        customImage:   unityci/editor:ubuntu-${{ env.UNITY_VERSION }}-base-3
        testMode:      editmode
        customParameters: "-nographics"
        artifactsPath: ./testReports/${{ env.TARGET_PLATFORM }}

    - if: always() && steps.tests.outcome != 'success'
      uses: actions/upload-artifact@v4
      with:
        name: Raw Test Results
        path: testReports/${{ env.TARGET_PLATFORM }}/editmode-results.xml

    - if: always()
      run: |
        mkdir -p testReports/${{ env.TARGET_PLATFORM }}
        cp -r ./Tools/ExtentReports/* testReports/${{ env.TARGET_PLATFORM }}/

    - if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test results
        path: ./testReports/${{ env.TARGET_PLATFORM }}
