name: Tests

on:
  push:
    branches: [ develop ]
    paths:
      - "Tools/UnityLicense.ulf"
      - "UnityProject/**"
      - ".github/workflows/**"
      - "Docker/**"
  pull_request:
    branches: [ develop ]
    paths:
      - "Tools/UnityLicense.ulf"
      - "UnityProject/**"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UNITY_VERSION: 6000.0.48f1
  PROJECT_PATH: UnityProject
  TARGET_PLATFORM: StandaloneWindows64

jobs:
  performTest:
    name: Unit tests
    runs-on: ubuntu-latest

    env: #TODO REMOVE
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check UNITY_LICENSE length
      run: |
        echo "bytes=${#UNITY_LICENSE}"

    - name: Cache Library
      uses: actions/cache@v4
      with:
        path: ${{ env.PROJECT_PATH }}/Library
        key: Library2-${{ env.PROJECT_PATH }}-${{ env.UNITY_VERSION }}-${{ runner.os }}
        restore-keys: |
          Library2-${{ env.PROJECT_PATH }}-${{ env.UNITY_VERSION }}-
          Library2-${{ env.PROJECT_PATH }}-

    - name: Swap 4 GB
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 4

    - name: Run tests
      id: tests
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        customParameters: "-nographics"
        projectPath: ${{ env.PROJECT_PATH }}

        customImage: unityci/editor:ubuntu-6000.0.48f1-base-3
        artifactsPath: ./testReports/${{ env.TARGET_PLATFORM }}
        testMode: editmode
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload raw XML (fail-only)
      if: always() && steps.tests.outcome != 'success'
      uses: actions/upload-artifact@v4
      with:
        name: Raw Test Results
        path: testReports/${{ env.TARGET_PLATFORM }}/editmode-results.xml

    - name: Copy ExtentReports
      if: always()
      run: |
        mkdir -p testReports/${{ env.TARGET_PLATFORM }}/
        cp -r ./Tools/ExtentReports/* testReports/${{ env.TARGET_PLATFORM }}/

    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test results
        path: ./testReports/${{ env.TARGET_PLATFORM }}
